phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - pip install --upgrade pip
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint dcrm || true
              pylint devops || true
              pylint website || true
artifacts:
    files:
        - '**/*'