version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Prebuild ops"
      #- sudo apt-get update
      - pip --version
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - echo "Pylint static code analysis"
      - pylint dcrm || true
      - pylint website --disable=C,R --ignore=views.py *.py || true
 
 
  build:
    commands:
      - echo "Building the application"
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'